/**
  This canvas was entirely generated by Claude.
 */
'use client';

import { useEffect, useRef } from 'react';
import { GamePhase } from '@/lib/types';
import { TIER_HEX, tierFor } from '@/lib/multiplierColors';

interface Props {
  phase: GamePhase;
  multiplier: number;
  startsAt?: number;
  crashPoint?: number;
}

interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  r: number;
  life: number;
}

export function AviatorCanvas(props: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const propsRef = useRef(props);
  propsRef.current = props;

  const particlesRef = useRef<Particle[]>([]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const parent = canvas.parentElement;
    if (!parent) return;

    const dpr = window.devicePixelRatio || 1;
    const size = { w: 0, h: 0 };

    const resize = () => {
      const rect = parent.getBoundingClientRect();
      size.w = rect.width;
      size.h = rect.height;
      canvas.width = Math.max(1, Math.floor(rect.width * dpr));
      canvas.height = Math.max(1, Math.floor(rect.height * dpr));
    };
    resize();

    const ro = new ResizeObserver(resize);
    ro.observe(parent);

    let raf = 0;
    let lastTime = performance.now();

    const draw = (now: number) => {
      const dt = Math.min(0.1, (now - lastTime) / 1000);
      lastTime = now;

      const W = size.w;
      const H = size.h;
      const { phase, multiplier, startsAt, crashPoint } = propsRef.current;

      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, W, H);

      if (phase === 'RUNNING' && multiplier > 10) {
        const intensity = Math.min(10, (multiplier - 10) / 3);
        ctx.translate(
          (Math.random() - 0.5) * intensity,
          (Math.random() - 0.5) * intensity,
        );
      }

      drawBackground(ctx, W, H, phase, multiplier);

      const padL = 60;
      const padB = 60;
      const plotW = W - padL - 30;
      const plotH = H - padB - 60;
      const originX = padL;
      const originY = H - padB;

      const t = Math.min(1, (multiplier - 1) / 5);
      const easedX = 1 - Math.pow(1 - t, 1.6);
      const easedY = Math.pow(t, 0.7);
      const planeX = originX + plotW * (0.05 + 0.95 * easedX);
      const planeY = originY - plotH * easedY;

      const tier = TIER_HEX[tierFor(multiplier)];

      if (phase !== 'WAITING') {
        const curveColor = phase === 'CRASHED' ? tier.strokeDim : tier.stroke;

        const gradient = ctx.createLinearGradient(
          originX,
          originY,
          originX,
          planeY,
        );
        gradient.addColorStop(0, tier.fillRgbaTransparent);
        gradient.addColorStop(1, tier.fillRgba);

        ctx.beginPath();
        ctx.moveTo(originX, originY);
        ctx.quadraticCurveTo(planeX, originY, planeX, planeY);
        ctx.lineTo(planeX, originY);
        ctx.closePath();
        ctx.fillStyle = gradient;
        ctx.fill();

        ctx.beginPath();
        ctx.moveTo(originX, originY);
        ctx.quadraticCurveTo(planeX, originY, planeX, planeY);
        ctx.strokeStyle = curveColor;
        ctx.lineWidth = 3;
        ctx.shadowColor = tier.glow;
        ctx.shadowBlur = phase === 'CRASHED' ? 0 : 12;
        ctx.stroke();
        ctx.shadowBlur = 0;
      }

      if (phase === 'RUNNING') {
        const count = multiplier > 5 ? 3 : 2;
        for (let i = 0; i < count; i++) {
          particlesRef.current.push({
            x: planeX - 16,
            y: planeY + 4,
            vx: -60 - Math.random() * 60,
            vy: -15 + Math.random() * 30,
            r: 4 + Math.random() * 4,
            life: 1,
          });
        }
      }

      particlesRef.current = particlesRef.current.filter((p) => {
        p.life -= dt * 1.4;
        if (p.life <= 0) return false;
        p.x += p.vx * dt;
        p.y += p.vy * dt;
        const alpha = p.life * 0.35;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r * (0.4 + p.life * 0.8), 0, Math.PI * 2);
        ctx.fillStyle = `rgba(220, 220, 230, ${alpha})`;
        ctx.fill();
        return true;
      });

      if (phase !== 'WAITING') {
        drawPlane(ctx, planeX, planeY, phase === 'CRASHED', tier.stroke);
      }

      drawCenterText(ctx, W, H, phase, multiplier, crashPoint, startsAt, tier);

      raf = requestAnimationFrame(draw);
    };

    raf = requestAnimationFrame(draw);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="absolute inset-0 block rounded-2xl"
      style={{ touchAction: 'none', width: '100%', height: '100%' }}
    />
  );
}

function drawBackground(
  ctx: CanvasRenderingContext2D,
  W: number,
  H: number,
  phase: GamePhase,
  multiplier: number,
) {
  const bg = ctx.createRadialGradient(W / 2, H / 2, 50, W / 2, H / 2, W);
  if (phase === 'CRASHED') {
    bg.addColorStop(0, '#2a0a14');
    bg.addColorStop(1, '#0b0810');
  } else {
    bg.addColorStop(0, '#15152a');
    bg.addColorStop(1, '#07070d');
  }
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  const offset = phase === 'RUNNING' ? (multiplier * 30) % 40 : 0;
  ctx.strokeStyle = 'rgba(255, 255, 255, 0.04)';
  ctx.lineWidth = 1;
  for (let x = -offset; x < W; x += 40) {
    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x, H);
    ctx.stroke();
  }
  for (let y = -offset; y < H; y += 40) {
    ctx.beginPath();
    ctx.moveTo(0, y);
    ctx.lineTo(W, y);
    ctx.stroke();
  }
}

function drawPlane(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  crashed: boolean,
  strokeColor: string,
) {
  ctx.save();
  ctx.translate(x, y);
  ctx.rotate(crashed ? Math.PI / 5 : -Math.PI / 7);
  ctx.fillStyle = crashed ? '#2a2a3a' : '#ffffff';
  ctx.strokeStyle = strokeColor;
  ctx.lineWidth = 2;

  ctx.beginPath();
  ctx.moveTo(-22, 0);
  ctx.quadraticCurveTo(-10, -7, 18, -5);
  ctx.lineTo(26, 0);
  ctx.lineTo(18, 5);
  ctx.quadraticCurveTo(-10, 7, -22, 0);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  ctx.beginPath();
  ctx.moveTo(-2, -3);
  ctx.lineTo(-14, -18);
  ctx.lineTo(4, -3);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  ctx.beginPath();
  ctx.moveTo(-2, 3);
  ctx.lineTo(-14, 14);
  ctx.lineTo(4, 3);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  ctx.beginPath();
  ctx.moveTo(-22, -2);
  ctx.lineTo(-28, -10);
  ctx.lineTo(-18, -2);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  ctx.restore();
}

function drawCenterText(
  ctx: CanvasRenderingContext2D,
  W: number,
  H: number,
  phase: GamePhase,
  multiplier: number,
  crashPoint: number | undefined,
  startsAt: number | undefined,
  tier: (typeof TIER_HEX)[keyof typeof TIER_HEX],
) {
  const cx = W / 2;
  const cy = H / 2 - 10;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  if (phase === 'WAITING') {
    const remaining = Math.max(0, ((startsAt || 0) - Date.now()) / 1000);
    ctx.font = '600 18px ui-sans-serif, system-ui';
    ctx.fillStyle = 'rgba(245, 245, 247, 0.65)';
    ctx.fillText('Próxima rodada em', cx, cy - 50);
    ctx.font = 'bold 88px ui-sans-serif, system-ui';
    ctx.fillStyle = '#ffffff';
    ctx.fillText(remaining.toFixed(1) + 's', cx, cy + 20);
  } else if (phase === 'CRASHED') {
    ctx.font = 'bold 28px ui-sans-serif, system-ui';
    ctx.fillStyle = tier.glow;
    ctx.fillText('VOOU EMBORA', cx, cy - 60);
    ctx.font = 'bold 108px ui-sans-serif, system-ui';
    ctx.fillStyle = tier.glow;
    ctx.shadowColor = tier.glow;
    ctx.shadowBlur = 30;
    ctx.fillText((crashPoint ?? multiplier).toFixed(2) + 'x', cx, cy + 20);
    ctx.shadowBlur = 0;
  } else {
    ctx.font = 'bold 128px ui-sans-serif, system-ui';
    ctx.fillStyle = '#ffffff';
    ctx.shadowColor = tier.glow;
    ctx.shadowBlur = 35;
    ctx.fillText(multiplier.toFixed(2) + 'x', cx, cy);
    ctx.shadowBlur = 0;
  }
}
